name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [

  { pattern = "zerostore.ggff.net", custom_domain = true },
  { pattern = "ava.game.naver.com.zerostore.ggff.net", custom_domain = true },
  { pattern = "quiz.int.vidio.com.zerostore.ggff.net", custom_domain = true },
  { pattern = "graph.instagram.com.zerostore.ggff.net", custom_domain = true },
  { pattern = "help.viu.com.zerostore.ggff.net", custom_domain = true },
  { pattern = "support.zoom.us.zerostore.ggff.net", custom_domain = true },
  { pattern = "cache.netflix.com.zerostore.ggff.net", custom_domain = true },
  { pattern = "graph.facebook.com.zerostore.ggff.net", custom_domain = true },
  { pattern = "dogseechew.com.zerostore.ggff.net", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "a506bfb8ec674aed8b8ef0a3fccb6954"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "214e9352-22dd-4add-8464-02473d8f7e7f"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/dit1304/Cloud/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/dit1304/Cloud/main/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/dit1304/Cloud/main/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/dit1304/Cloud/main/web/converter.html"
